# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9b47a98e715912aa2d3844f733dd7f55e1a683c5a85da3ce33740990eb6e7ed6d9be10ee08c63370b9f1f71e45bcfc80caef1d72087ec2a4fe70881a16d930c

test:
  secret_key_base: d1fdc37652cbba01b661cb01da83a52e47d567db43a6c899d77f0831a208d89500257317339cadca2946c81f9ad2ede28f7d18de22e8125e8a436a504f6dced8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
